security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        memory_users:
            memory:
                users:
                    '%env(MEMORY_DEFAULT_EMAIL)%': {
                        password: '%env(MEMORY_DEFAULT_PWD)%',
                        roles: [ 'ROLE_ADMIN']
                    }
        app_users:
            entity:
                class: App\Entity\User
                property: email
        all_users:
            chain:
                providers: ['app_users', 'memory_users']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: all_users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/profile, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/resident, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/room, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10