twig:
    default_path: '%kernel.project_dir%/templates/'
    form_themes: ['tailwind_2_layout.html.twig','Form/vich_fields.html.twig']
    globals:
        room: '@App\Dto\Room'

when@test:
    twig:
        strict_variables: true
