vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        base:
            uri_prefix: /images/base
            upload_destination: '%kernel.project_dir%/public/images/base'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        resident:
            uri_prefix: /images/resident
            upload_destination: '%kernel.project_dir%/public/images/resident'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
